# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Juniper Divination and Witchery
email: arabella@juniperdivination.com
description: >- # this means to ignore newlines until "baseurl:"
  Tarot helps us navigate life’s transitions with grace and compassion. It illuminates the unconscious, encourages self-reflection, and aids us in making informed choices. As your intuitive tarot reader, I will combine my intuition with my understanding of the tarot to see your core self, your struggles, and the most loving way for you to proceed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juniperdivination.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-datapage-generator
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  implementation: sass-embedded
  sass_dir: _sass
  style: compressed

categories-order:
 - Simple
 - Lunar
 - Healing and Health
 - Love and Relationships
 - Holidays
 - Spirit Communication

page_gen_dirs: false

page_gen:
- data: free-tarot-spreads
  template: free-tarot-spread
  dir: free-tarot-spreads
  name: name
  title: title
  img: img
  category: category
  description: description

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
